name: updatenode

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      - ipUrl.txt
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v4
    - name: 执行任务 -update IP and node
      run: |
        curl -o sub/xxx.txt ${{variables.v1}}

    - name: Pushes
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{secrets.ACTIONS_USE}}
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/proxies'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'cf node update'
