name: update_cf_node

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      - ipurl.txt
      - all.txt
  workflow_dispatch:
  workflow_run:
    workflows: ["pushIP","update_proxy_ip","alive IP Zone"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v4
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai' 
    - name: 执行任务 -update node
      run: |
        mkdir sub
        cd ./sub
        echo "$(date +'%Y-%m-%d %H:%M:%S')" > cf_ip_update_time.txt
    - name: Pushes
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{secrets.ACTIONS_USE}}
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/proxies'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'cf node update'
